@baseUrl = http://localhost:5042
@token = 

### Get all users (Admin only)
GET {{baseUrl}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

###

### Get user by ID (Admin only)
GET {{baseUrl}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

###

### Update user (Admin only)
PUT {{baseUrl}}/api/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "displayName": "John Doe",
  "role": "Mentor"
}

###

### Delete user (Admin only)
DELETE {{baseUrl}}/api/users/1
Authorization: Bearer {{token}}

###
